template = "https://github.com/giellalt/template-lang-und"
rev_id = 280
template_sha = "6beee360d8349c39749ac477719ead241493924c"

[replacements]
__GLOTTOLOG_ID__ = "telu1262"
__REPO__ = "lang-tel"
__UND2C__ = "te"
__UNDEFINED__ = "Telugu"
__UND__ = "tel"
